import type { ID, PrincípioCanônico, Etapa, ProgramaArea, Risco, Prancha } from "./types";

const uid = (p: string, n: number): ID => `${p}-${String(n).padStart(3, "0")}`;

export const CANONICAL_PRINCIPLES: PrincípioCanônico[] = [
  {
    id: uid("princ", 1),
    enunciado:
      "A Greenhouse Library é o coração da experiência — centro emocional e visual para onde convergem vistas, percursos e pausas.",
    categoria: "essencia",
    imutavel: true,
    descricao:
      "Não pode ser reduzida em área, em hierarquia ou em desempenho térmico/acústico/solar por decisões de implantação.",
  },
  {
    id: uid("princ", 2),
    enunciado:
      "A cidadela doméstica é compacta e introvertida: o conjunto principal permanece concentrado; a área rural amplia paisagem e produção, não dissolve a casa.",
    categoria: "espacial",
    imutavel: true,
    descricao:
      "Pavilhões não se espalham aleatoriamente. Estruturas rurais ficam na periferia operacional.",
  },
  {
    id: uid("princ", 3),
    enunciado:
      "O Pavilhão A é doméstico, silencioso e acolhedor — sem ateliê nem laboratório.",
    categoria: "essencia",
    imutavel: true,
  },
  {
    id: uid("princ", 4),
    enunciado:
      "O Pavilhão B é pessoal, discreto e tecnicamente autônomo, subordinado visualmente à Casa Principal.",
    categoria: "hierarquia",
    imutavel: true,
    descricao:
      "Corpus, Mens, Ars e Otium coexistem; o laboratório olfativo (~20–25 m²) fica no térreo junto à infraestrutura e ao jardim aromático.",
  },
  {
    id: uid("princ", 5),
    enunciado:
      "A hospitalidade parece parte da casa, não hotel ou alojamento institucional — com entrada, banho, apoio de cozinha e privacidade próprios.",
    categoria: "essencia",
    imutavel: true,
  },
  {
    id: uid("princ", 6),
    enunciado:
      "O siheyuan é estruturado por pátios, não apenas por corredores: sequência chegada → doméstico → Greenhouse → social → ofícios → aromático → contemplação.",
    categoria: "espacial",
    imutavel: true,
  },
  {
    id: uid("princ", 7),
    enunciado:
      "Nada é escondido de quem habita a casa. Quase tudo é escondido de quem está fora dela.",
    categoria: "carater",
    imutavel: true,
    descricao:
      "Exterior opaco e mineral; interior aberto para pátios e jardins. Coberturas profundas, passagens protegidas, água e sombra.",
  },
  {
    id: uid("princ", 8),
    enunciado:
      "A resiliência (energia, dados, água, segurança) é uma camada técnica discreta — percebida pela tranquilidade de funcionamento, nunca como tema visual.",
    categoria: "resiliencia",
    imutavel: true,
  },
  {
    id: uid("princ", 9),
    enunciado:
      "Materialidade canônica: pedra, madeira, cal, vidro e metal escuro. A arquitetura parece ter crescido como ordem doméstica ao longo do tempo.",
    categoria: "carater",
    imutavel: true,
  },
  {
    id: uid("princ", 10),
    enunciado:
      "A obra só termina quando o conjunto — inclusive o último artefato decorativo — estiver implantado.",
    categoria: "essencia",
    imutavel: true,
  },
];

export const CANONICAL_ETAPAS: Etapa[] = [
  {
    id: uid("etapa", 1),
    nome: "Contratação de arquiteto",
    ordem: 1,
    responsaveis: ["Guardião do briefing"],
    dependencias: [],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: ["Selecionar arquiteto alinhado aos princípios canônicos"],
    status: "nao-iniciada",
    criteriosConclusao: ["Contrato assinado", "Briefing canônico aceito pelo arquiteto"],
  },
  {
    id: uid("etapa", 2),
    nome: "Levantamento e estudos preliminares",
    ordem: 2,
    responsaveis: ["Arquiteto"],
    dependencias: [uid("etapa", 1)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: ["Levantamento topográfico", "Estudo de restrições ambientais e legais"],
  },
  {
    id: uid("etapa", 3),
    nome: "Anteprojeto",
    ordem: 3,
    responsaveis: ["Arquiteto"],
    dependencias: [uid("etapa", 2)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: ["Conflito entre implantação e princípio canônico"],
    status: "nao-iniciada",
    criteriosConclusao: ["Quatro pranchas-base aprovadas", "Programa de áreas definido"],
  },
  {
    id: uid("etapa", 4),
    nome: "Projetos legais e executivos",
    ordem: 4,
    responsaveis: ["Arquiteto"],
    dependencias: [uid("etapa", 3)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: ["Projetos legal e executivo completos"],
  },
  {
    id: uid("etapa", 5),
    nome: "Licenciamento",
    ordem: 5,
    responsaveis: ["Arquiteto", "Guardião do briefing"],
    dependencias: [uid("etapa", 4)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: ["Restrição ambiental pode inviabilizar capela externa"],
    status: "nao-iniciada",
    criteriosConclusao: ["Licenças emitidas"],
  },
  {
    id: uid("etapa", 6),
    nome: "Orçamento",
    ordem: 6,
    responsaveis: ["Gestor de obra"],
    dependencias: [uid("etapa", 4)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: ["Orçamento fechado por etapa"],
  },
  {
    id: uid("etapa", 7),
    nome: "Contratação",
    ordem: 7,
    responsaveis: ["Gestor de obra"],
    dependencias: [uid("etapa", 6)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: ["Contratos de obra assinados"],
  },
  {
    id: uid("etapa", 8),
    nome: "Obra",
    ordem: 8,
    responsaveis: ["Gestor de obra", "Arquiteto"],
    dependencias: [uid("etapa", 7)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: ["Improvisações de obra diluindo intenção"],
    status: "nao-iniciada",
    criteriosConclusao: ["Núcleo construído", "Infraestrutura rural instalada"],
  },
  {
    id: uid("etapa", 9),
    nome: "Paisagismo",
    ordem: 9,
    responsaveis: ["Arquiteto"],
    dependencias: [uid("etapa", 8)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: ["Pátios e jardim aromático implantados"],
  },
  {
    id: uid("etapa", 10),
    nome: "Instalação de equipamentos",
    ordem: 10,
    responsaveis: ["Gestor de obra"],
    dependencias: [uid("etapa", 8)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: ["Equipamentos recebidos e instalados"],
  },
  {
    id: uid("etapa", 11),
    nome: "Decoração",
    ordem: 11,
    responsaveis: ["Arquiteto"],
    dependencias: [uid("etapa", 10)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: ["Artefatos decorativos aprovados e instalados"],
  },
  {
    id: uid("etapa", 12),
    nome: "Implantação do último artefato",
    ordem: 12,
    responsaveis: ["Guardião do briefing"],
    dependencias: [uid("etapa", 11)],
    documentoIds: [],
    orcamento: 0,
    custoReal: 0,
    riscos: [],
    status: "nao-iniciada",
    criteriosConclusao: [
      "Todos os artefatos pendentes = executados",
      "Checklist de entrega por ambiente completo",
    ],
  },
];

export const CANONICAL_PROGRAMA: ProgramaArea[] = [
  { id: uid("pa", 1), ambienteKey: "portal", nome: "Portão e filtro de chegada", pavilhao: "Acesso", area: 0, versao: "v1" },
  { id: uid("pa", 2), ambienteKey: "chegada", nome: "Alameda", pavilhao: "Acesso", area: 0, versao: "v1" },
  { id: uid("pa", 3), ambienteKey: "pavilhao-a", nome: "Pavilhão A — Casa Principal", pavilhao: "Pavilhão A", area: 600, versao: "v1" },
  { id: uid("pa", 4), ambienteKey: "greenhouse-library", nome: "Greenhouse Library", pavilhao: "Coração", area: 180, versao: "v1" },
  { id: uid("pa", 5), ambienteKey: "pavilhao-b", nome: "Pavilhão B — Ofícios (Corpus/Mens/Ars/Otium)", pavilhao: "Pavilhão B", area: 350, versao: "v1" },
  { id: uid("pa", 6), ambienteKey: "laboratorio-perfumaria", nome: "Laboratório de perfumaria/incensaria", pavilhao: "Pavilhão B", area: 24, versao: "v1" },
  { id: uid("pa", 7), ambienteKey: "pavilhao-c", nome: "Pavilhão C — Ofícios Alimentares", pavilhao: "Pavilhão C", area: 220, versao: "v1" },
  { id: uid("pa", 8), ambienteKey: "patio-chegada", nome: "Pátio de chegada", pavilhao: "Pátios", area: 0, versao: "v1" },
  { id: uid("pa", 9), ambienteKey: "patio-domestico", nome: "Pátio doméstico", pavilhao: "Pátios", area: 0, versao: "v1" },
  { id: uid("pa", 10), ambienteKey: "patio-social", nome: "Pátio social", pavilhao: "Pátios", area: 0, versao: "v1" },
  { id: uid("pa", 11), ambienteKey: "patio-oficios", nome: "Pátio de ofícios", pavilhao: "Pátios", area: 0, versao: "v1" },
  { id: uid("pa", 12), ambienteKey: "jardim-aromatico", nome: "Jardim aromático", pavilhao: "Pátios", area: 0, versao: "v1" },
  { id: uid("pa", 13), ambienteKey: "jardim-contemplacao", nome: "Jardim de contemplação", pavilhao: "Pátios", area: 0, versao: "v1" },
  { id: uid("pa", 14), ambienteKey: "capela-domestica", nome: "Capela doméstica interna", pavilhao: "Espiritual", area: 20, versao: "v1" },
  { id: uid("pa", 15), ambienteKey: "capela-externa", nome: "Capela ortodoxa externa (8–10 pessoas)", pavilhao: "Espiritual", area: 40, versao: "v1" },
  { id: uid("pa", 16), ambienteKey: "zona-produtiva", nome: "Zona Produtiva (horta, pomar, apiário)", pavilhao: "Rural", area: 0, versao: "v1" },
  { id: uid("pa", 17), ambienteKey: "infra-rural", nome: "Infraestrutura rural e camada técnica", pavilhao: "Infraestrutura", area: 0, versao: "v1" },
];

export const REFERENCE_PRANCHAS: Prancha[] = [
  {
    id: uid("prancha", 1),
    ambienteKey: "infra-rural",
    titulo: "Diagrama de camadas da propriedade",
    intencaoEspacial: "Estrada → portão/filtro → alameda → cidadela doméstica → jardim/zona produtiva → campos/bosque. Estrutura concêntrica: o conjunto principal concentrado e introvertido; a área rural amplia paisagem e produção sem dissolver a casa.",
    intencaoEmocional: "Transição gradual entre público, familiar, pessoal, produtivo e natural. A propriedade protegida e silenciosa vista de fora; aberta para pátios e jardins de dentro.",
    principioIds: [uid("princ", 2), uid("princ", 7)],
    materiais: "pedra, madeira, cal, vidro, metal escuro",
    referencias: "Propriedade-cidadela; ordem doméstica crescida ao longo do tempo",
    status: "aprovado",
    alternativas: "Núcleo compacto (1.600–2.400 m²) vs. dispersão rural — apenas a primeira é canônica",
    createdAt: "",
  },
  {
    id: uid("prancha", 2),
    ambienteKey: "pavilhao-a",
    titulo: "Planta conceitual do núcleo siheyuan",
    intencaoEspacial: "Siheyuan estruturado por pátios: chegada → doméstico → Greenhouse → social → ofícios → aromático → contemplação. Pavilhão A (doméstico), Greenhouse Library (coração), Pavilhão B (ofícios), Pavilhão C (ofícios alimentares), hospitalidade independente.",
    intencaoEmocional: "A Greenhouse Library não precisa estar geometricamente no centro, mas é o centro da experiência: para onde convergem vistas, percursos e pausas.",
    principioIds: [uid("princ", 1), uid("princ", 6)],
    materiais: "pedra, madeira, cal, vidro, metal escuro",
    referencias: "Sequência de pátios; cidadela introvertida",
    status: "aprovado",
    alternativas: "Deslocamentos de pavilhões são admissíveis; reduzir a Greenhouse é proibido",
    createdAt: "",
  },
  {
    id: uid("prancha", 3),
    ambienteKey: "chegada",
    titulo: "Sequência de chegada e percurso interno",
    intencaoEspacial: "Portão e filtro de chegada → alameda → pátio de chegada → cidadela. Percurso interno: pátio doméstico → Greenhouse Library → pátio social → pátio de ofícios → jardim aromático → jardim de contemplação.",
    intencaoEmocional: "Nada é escondido de quem habita a casa; quase tudo é escondido de quem está fora. Coberturas profundas, passagens protegidas, água e sombra.",
    principioIds: [uid("princ", 7), uid("princ", 6)],
    materiais: "pedra, madeira, cal, vidro, metal escuro",
    referencias: "Transições graduais; exterior opaco, interior aberto",
    status: "aprovado",
    alternativas: "",
    createdAt: "",
  },
  {
    id: uid("prancha", 4),
    ambienteKey: "zona-produtiva",
    titulo: "Zoneamento rural com núcleo, produção, infraestrutura, campos e bosque",
    intencaoEspacial: "Núcleo doméstico compacto → jardim aromático + zona produtiva (horta, pomar, ervas, galinhas, coelhos, apiário, compostagem, estufas) → infraestrutura rural (acesso de serviço, reservação, efluentes, energia, resíduos) → campos, pomar, bosque, capela externa.",
    intencaoEmocional: "A resiliência é camada técnica discreta — percebida pela tranquilidade de funcionamento, nunca como tema visual. Estruturas rurais na periferia operacional, nunca competindo com a cidadela.",
    principioIds: [uid("princ", 2), uid("princ", 8)],
    materiais: "pedra, madeira, cal, metal escuro",
    referencias: "Periferia operacional; camadas produtivas/paisagísticas/técnicas",
    status: "aprovado",
    alternativas: "Infraestrutura necessária vs. desejável vs. possibilidades futuras — sempre na periferia",
    createdAt: "",
  },
];

export const CANONICAL_RISCOS: Risco[] = [
  {
    id: uid("risco", 1),
    descricao: "Decisão de implantação reduz a Greenhouse Library",
    probabilidade: "media",
    impacto: "alto",
    mitigacao: "Alerta canônico bloqueia redução de área/hierarquia da Greenhouse Library",
    canonico: true,
    principioId: uid("princ", 1),
    resolvido: false,
  },
  {
    id: uid("risco", 2),
    descricao: "Estruturas rurais competindo com a cidadela doméstica",
    probabilidade: "media",
    impacto: "alto",
    mitigacao: "Periferia operacional obrigatória; cidadela permanece compacta",
    canonico: true,
    principioId: uid("princ", 2),
    resolvido: false,
  },
  {
    id: uid("risco", 3),
    descricao: "Improvisação de obra dissolvendo a intenção arquitetônica",
    probabilidade: "alta",
    impacto: "alto",
    mitigacao: "Toda alteração registrada como Decisão com verificação canônica",
    canonico: true,
    principioId: uid("princ", 9),
    resolvido: false,
  },
];
